### ISSUE TITLE
wfm.py使用的Dict翻譯

### ISSUE THREAD

**Issue by lonnstyle** [lonnstyle/DiscordBotExt#10]
<s>https://gitlocalize.com/repo/5556/zh/dict/items_en.json</s>
終止編寫官方Dict,將在wf.m更新後使用wf.m翻譯
https://docs.google.com/spreadsheets/d/1AMxTBp1_HdVbjdxnpTGqy_16OoP-CBeBc9117ZXGhEQ/edit?usp=sharing

**Comment by MeowXiaoXiang** [comment]
喔~wf.m翻譯
